loadAllCP(){
    CP_tempatFoto = buatCPDanLabel(-201.7664,-25.4403,1002.2734, "Silahkan cetak foto disini", 1.0);
    
    // Spot pembelian di dalam market
    CP_spotBarangMarket[0] = buatCPDanLabel(-4.2324, -176.4322, 1003.5469, "Barang-barang\nBeli disini!", 1.0);
    CP_spotBarangMarket[1] = buatCPDanLabel(-9.7521, -169.9181, 1003.5469, "Barang-barang\nBeli disini!", 1.0);
    CP_spotBarangMarket[2] = buatCPDanLabel(-34.2435, -182.2766, 1003.5469, "Barang-barang\nBeli disini!", 1.0);
    CP_spotBarangMarket[3] = buatCPDanLabel(-34.2461, -172.7712, 1003.5469, "Barang-barang\nBeli disini!", 1.0);
}