loadAllCP(){
    CP_tempatFoto = buatCPDanLabel(-201.7664,-25.4403,1002.2734, "Silahkan cetak foto. disini\""GREEN"Lakukan pencetakan foto disini.", 1.0);
    
    // Spot pembelian di dalam market
    CP_spotBarangMarket[0] = buatCPDanLabel(-4.2324, -176.4322, 1003.5469, "Barang-barang\nBeli disini!", 1.0);
    CP_spotBarangMarket[1] = buatCPDanLabel(-9.7521, -169.9181, 1003.5469, "Barang-barang\nBeli disini!", 1.0);
    CP_spotBarangMarket[2] = buatCPDanLabel(-34.2435, -182.2766, 1003.5469, "Barang-barang\nBeli disini!", 1.0);
    CP_spotBarangMarket[3] = buatCPDanLabel(-34.2461, -172.7712, 1003.5469, "Barang-barang\nBeli disini!", 1.0);

    // Spot beli skin di toko baju
    CP_spotBeliSkin[0] = buatCPDanLabel(152.3235,-83.6493,1001.8047, "Skin normal\n"GREEN"Beli skin disini!", 1.0);
    CP_spotBeliSkin[1] = buatCPDanLabel(167.2928,-89.5232,1001.8047, "Skin normal\n"GREEN"Beli skin disini!", 1.0);
    CP_spotBeliSkin[2] = buatCPDanLabel(175.2670,-83.3361,1001.8047, "Skin normal\n"GREEN"Beli skin disini!", 1.0);

    // Spot ganti skin
    CP_spotGantiSkin = buatCPDanLabel(181.0340,-91.6368,1002.0234, "Ganti skin\n"YELLOW"Refresh skin anda disini.", 1.0);

    // City Hall Respsionis
    CP_resepsionisCityHall = buatCPDanLabel(-501.1717,294.3522,2001.0950, "Resepsionis Pemerintah Los Santos\n"BLUE"Silahkan kesini untuk melakukan pengurusan data!", 1.0);
}