loadAllPickup(){
    PU_tempatFoto[ENTER_PICKUP] = buatPickupDanLabel(1318, 1111.9841, -1370.0327, 13.9844, "Tempat foto dan cetak foto\n"GREEN"Pintu Masuk");
    PU_tempatFoto[EXIT_PICKUP] = buatPickupDanLabel(1318, -204.3725, -27.3480, 1002.2734, "Tempat foto dan cetak foto\n"GREEN"Pintu Keluar");

    // minimarket yang ada mappingan
    PU_miniMarket[0][ENTER_PICKUP] = buatPickupDanLabel(1318, 1352.3239, -1759.2528, 13.5078, "Minimarket A\n"GREEN"Pintu Masuk");
    PU_miniMarket[0][EXIT_PICKUP] = buatPickupDanLabel(1318, -25.8201, -188.2510, 1003.5469, "Minimarket A\n"GREEN"Pintu Keluar");
}