/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new Text:HUD_Stats_PB[5];
new PlayerText:HUD_Stats[MAX_PLAYERS][1];
new PlayerBar:HUD_Stats_Bar[MAX_PLAYERS][2];

//Textdraws
HUD_Stats_PB[0] = TextDrawCreate(502.000000, 344.000000, "Lapar");
TextDrawFont(HUD_Stats_PB[0], 1);
TextDrawLetterSize(HUD_Stats_PB[0], 0.400000, 1.649999);
TextDrawTextSize(HUD_Stats_PB[0], 400.000000, 17.000000);
TextDrawSetOutline(HUD_Stats_PB[0], 1);
TextDrawSetShadow(HUD_Stats_PB[0], 0);
TextDrawAlignment(HUD_Stats_PB[0], 1);
TextDrawColor(HUD_Stats_PB[0], -1);
TextDrawBackgroundColor(HUD_Stats_PB[0], 255);
TextDrawBoxColor(HUD_Stats_PB[0], 50);
TextDrawUseBox(HUD_Stats_PB[0], 0);
TextDrawSetProportional(HUD_Stats_PB[0], 1);
TextDrawSetSelectable(HUD_Stats_PB[0], 0);

HUD_Stats_PB[1] = TextDrawCreate(562.000000, 344.000000, "HUD:radar_pizza");
TextDrawFont(HUD_Stats_PB[1], 4);
TextDrawLetterSize(HUD_Stats_PB[1], 0.600000, 2.000000);
TextDrawTextSize(HUD_Stats_PB[1], 15.500000, 14.000000);
TextDrawSetOutline(HUD_Stats_PB[1], 1);
TextDrawSetShadow(HUD_Stats_PB[1], 0);
TextDrawAlignment(HUD_Stats_PB[1], 1);
TextDrawColor(HUD_Stats_PB[1], -1);
TextDrawBackgroundColor(HUD_Stats_PB[1], 255);
TextDrawBoxColor(HUD_Stats_PB[1], 50);
TextDrawUseBox(HUD_Stats_PB[1], 1);
TextDrawSetProportional(HUD_Stats_PB[1], 1);
TextDrawSetSelectable(HUD_Stats_PB[1], 0);

HUD_Stats_PB[2] = TextDrawCreate(502.000000, 391.000000, "Haus");
TextDrawFont(HUD_Stats_PB[2], 1);
TextDrawLetterSize(HUD_Stats_PB[2], 0.400000, 1.649999);
TextDrawTextSize(HUD_Stats_PB[2], 400.000000, 17.000000);
TextDrawSetOutline(HUD_Stats_PB[2], 1);
TextDrawSetShadow(HUD_Stats_PB[2], 0);
TextDrawAlignment(HUD_Stats_PB[2], 1);
TextDrawColor(HUD_Stats_PB[2], -1);
TextDrawBackgroundColor(HUD_Stats_PB[2], 255);
TextDrawBoxColor(HUD_Stats_PB[2], 50);
TextDrawUseBox(HUD_Stats_PB[2], 0);
TextDrawSetProportional(HUD_Stats_PB[2], 1);
TextDrawSetSelectable(HUD_Stats_PB[2], 0);

HUD_Stats_PB[3] = TextDrawCreate(562.000000, 391.000000, "HUD:radar_diner");
TextDrawFont(HUD_Stats_PB[3], 4);
TextDrawLetterSize(HUD_Stats_PB[3], 0.600000, 2.000000);
TextDrawTextSize(HUD_Stats_PB[3], 15.500000, 14.000000);
TextDrawSetOutline(HUD_Stats_PB[3], 1);
TextDrawSetShadow(HUD_Stats_PB[3], 0);
TextDrawAlignment(HUD_Stats_PB[3], 1);
TextDrawColor(HUD_Stats_PB[3], -1);
TextDrawBackgroundColor(HUD_Stats_PB[3], 255);
TextDrawBoxColor(HUD_Stats_PB[3], 50);
TextDrawUseBox(HUD_Stats_PB[3], 1);
TextDrawSetProportional(HUD_Stats_PB[3], 1);
TextDrawSetSelectable(HUD_Stats_PB[3], 0);

HUD_Stats_PB[4] = TextDrawCreate(567.000000, 328.000000, "_");
TextDrawFont(HUD_Stats_PB[4], 1);
TextDrawLetterSize(HUD_Stats_PB[4], 0.600000, 13.800003);
TextDrawTextSize(HUD_Stats_PB[4], 178.500000, 148.500000);
TextDrawSetOutline(HUD_Stats_PB[4], 1);
TextDrawSetShadow(HUD_Stats_PB[4], 0);
TextDrawAlignment(HUD_Stats_PB[4], 2);
TextDrawColor(HUD_Stats_PB[4], -1);
TextDrawBackgroundColor(HUD_Stats_PB[4], 255);
TextDrawBoxColor(HUD_Stats_PB[4], 135);
TextDrawUseBox(HUD_Stats_PB[4], 1);
TextDrawSetProportional(HUD_Stats_PB[4], 1);
TextDrawSetSelectable(HUD_Stats_PB[4], 0);

HUD_Stats[playerid][0] = CreatePlayerTextDraw(playerid, 532.000000, 325.000000, "Preview_Model");
PlayerTextDrawFont(HUD_Stats[playerid][0], 5);
PlayerTextDrawLetterSize(HUD_Stats[playerid][0], 0.600000, 2.000000);
PlayerTextDrawTextSize(HUD_Stats[playerid][0], 153.500000, 165.000000);
PlayerTextDrawSetOutline(HUD_Stats[playerid][0], 0);
PlayerTextDrawSetShadow(HUD_Stats[playerid][0], 0);
PlayerTextDrawAlignment(HUD_Stats[playerid][0], 1);
PlayerTextDrawColor(HUD_Stats[playerid][0], -1);
PlayerTextDrawBackgroundColor(HUD_Stats[playerid][0], 0);
PlayerTextDrawBoxColor(HUD_Stats[playerid][0], 255);
PlayerTextDrawUseBox(HUD_Stats[playerid][0], 0);
PlayerTextDrawSetProportional(HUD_Stats[playerid][0], 1);
PlayerTextDrawSetSelectable(HUD_Stats[playerid][0], 0);
PlayerTextDrawSetPreviewModel(HUD_Stats[playerid][0], 0);
PlayerTextDrawSetPreviewRot(HUD_Stats[playerid][0], -10.000000, 0.000000, -20.000000, 1.000000);
PlayerTextDrawSetPreviewVehCol(HUD_Stats[playerid][0], 1, 1);


//Player Textdraws



/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
HUD_Stats_Bar[playerid][0] = CreatePlayerProgressBar(playerid, 503.000000, 365.000000, 81.500000, 7.000000, -65281, 100.000000, 0);
SetPlayerProgressBarValue(playerid, HUD_Stats_Bar[playerid][0], 50.000000);

HUD_Stats_Bar[playerid][1] = CreatePlayerProgressBar(playerid, 503.000000, 412.000000, 81.500000, 7.000000, 1097458175, 100.000000, 0);
SetPlayerProgressBarValue(playerid, HUD_Stats_Bar[playerid][1], 50.000000);

