/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new Text:TD_JamTanggal[2];

//Textdraws
TD_JamTanggal[0] = TextDrawCreate(548.000000, 24.000000, "00:00:00");
TextDrawFont(TD_JamTanggal[0], 3);
TextDrawLetterSize(TD_JamTanggal[0], 0.395833, 1.700000);
TextDrawTextSize(TD_JamTanggal[0], 400.000000, 17.000000);
TextDrawSetOutline(TD_JamTanggal[0], 1);
TextDrawSetShadow(TD_JamTanggal[0], 0);
TextDrawAlignment(TD_JamTanggal[0], 1);
TextDrawColor(TD_JamTanggal[0], -1);
TextDrawBackgroundColor(TD_JamTanggal[0], 255);
TextDrawBoxColor(TD_JamTanggal[0], 50);
TextDrawUseBox(TD_JamTanggal[0], 0);
TextDrawSetProportional(TD_JamTanggal[0], 1);
TextDrawSetSelectable(TD_JamTanggal[0], 0);

TD_JamTanggal[1] = TextDrawCreate(501.000000, 10.000000, "Rabu, 10 20 2000");
TextDrawFont(TD_JamTanggal[1], 3);
TextDrawLetterSize(TD_JamTanggal[1], 0.404166, 1.400000);
TextDrawTextSize(TD_JamTanggal[1], 859.500000, -250.000000);
TextDrawSetOutline(TD_JamTanggal[1], 1);
TextDrawSetShadow(TD_JamTanggal[1], 0);
TextDrawAlignment(TD_JamTanggal[1], 1);
TextDrawColor(TD_JamTanggal[1], -1);
TextDrawBackgroundColor(TD_JamTanggal[1], 255);
TextDrawBoxColor(TD_JamTanggal[1], 50);
TextDrawUseBox(TD_JamTanggal[1], 0);
TextDrawSetProportional(TD_JamTanggal[1], 1);
TextDrawSetSelectable(TD_JamTanggal[1], 0);


//Player Textdraws

/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
