/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new PlayerText:showItem[MAX_PLAYERS][6];

//Textdraws

//Player Textdraws
showItem[playerid][5] = CreatePlayerTextDraw(playerid, 314.000000, 98.000000, "_");
PlayerTextDrawFont(playerid, showItem[playerid][5], 1);
PlayerTextDrawLetterSize(playerid, showItem[playerid][5], 10.804163, 27.150005);
PlayerTextDrawTextSize(playerid, showItem[playerid][5], 40.000000, 356.000000);
PlayerTextDrawSetOutline(playerid, showItem[playerid][5], 1);
PlayerTextDrawSetShadow(playerid, showItem[playerid][5], 0);
PlayerTextDrawAlignment(playerid, showItem[playerid][5], 2);
PlayerTextDrawColor(playerid, showItem[playerid][5], -1);
PlayerTextDrawBackgroundColor(playerid, showItem[playerid][5], 255);
PlayerTextDrawBoxColor(playerid, showItem[playerid][5], 207);
PlayerTextDrawUseBox(playerid, showItem[playerid][5], 1);
PlayerTextDrawSetProportional(playerid, showItem[playerid][5], 1);
PlayerTextDrawSetSelectable(playerid, showItem[playerid][5], 0);

showItem[playerid][0] = CreatePlayerTextDraw(playerid, 157.000000, 145.000000, "Preview_Model");
PlayerTextDrawFont(playerid, showItem[playerid][0], 5);
PlayerTextDrawLetterSize(playerid, showItem[playerid][0], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, showItem[playerid][0], 112.500000, 150.000000);
PlayerTextDrawSetOutline(playerid, showItem[playerid][0], 0);
PlayerTextDrawSetShadow(playerid, showItem[playerid][0], 0);
PlayerTextDrawAlignment(playerid, showItem[playerid][0], 1);
PlayerTextDrawColor(playerid, showItem[playerid][0], -1);
PlayerTextDrawBackgroundColor(playerid, showItem[playerid][0], -131);
PlayerTextDrawBoxColor(playerid, showItem[playerid][0], -1);
PlayerTextDrawUseBox(playerid, showItem[playerid][0], 0);
PlayerTextDrawSetProportional(playerid, showItem[playerid][0], 1);
PlayerTextDrawSetSelectable(playerid, showItem[playerid][0], 0);
PlayerTextDrawSetPreviewModel(playerid, showItem[playerid][0], 0);
PlayerTextDrawSetPreviewRot(playerid, showItem[playerid][0], -10.000000, 0.000000, -20.000000, 1.000000);
PlayerTextDrawSetPreviewVehCol(playerid, showItem[playerid][0], 1, 1);

showItem[playerid][1] = CreatePlayerTextDraw(playerid, 143.000000, 110.000000, "INFO ITEM ~G~ COSINUS");
PlayerTextDrawFont(playerid, showItem[playerid][1], 2);
PlayerTextDrawLetterSize(playerid, showItem[playerid][1], 0.412499, 2.199999);
PlayerTextDrawTextSize(playerid, showItem[playerid][1], 484.500000, 17.000000);
PlayerTextDrawSetOutline(playerid, showItem[playerid][1], 1);
PlayerTextDrawSetShadow(playerid, showItem[playerid][1], 0);
PlayerTextDrawAlignment(playerid, showItem[playerid][1], 1);
PlayerTextDrawColor(playerid, showItem[playerid][1], -1);
PlayerTextDrawBackgroundColor(playerid, showItem[playerid][1], 255);
PlayerTextDrawBoxColor(playerid, showItem[playerid][1], 50);
PlayerTextDrawUseBox(playerid, showItem[playerid][1], 1);
PlayerTextDrawSetProportional(playerid, showItem[playerid][1], 1);
PlayerTextDrawSetSelectable(playerid, showItem[playerid][1], 0);

showItem[playerid][2] = CreatePlayerTextDraw(playerid, 284.000000, 167.000000, "Jumlah Item");
PlayerTextDrawFont(playerid, showItem[playerid][2], 2);
PlayerTextDrawLetterSize(playerid, showItem[playerid][2], 0.245830, 1.799998);
PlayerTextDrawTextSize(playerid, showItem[playerid][2], 404.000000, 15.000000);
PlayerTextDrawSetOutline(playerid, showItem[playerid][2], 1);
PlayerTextDrawSetShadow(playerid, showItem[playerid][2], 0);
PlayerTextDrawAlignment(playerid, showItem[playerid][2], 1);
PlayerTextDrawColor(playerid, showItem[playerid][2], -1);
PlayerTextDrawBackgroundColor(playerid, showItem[playerid][2], 255);
PlayerTextDrawBoxColor(playerid, showItem[playerid][2], 50);
PlayerTextDrawUseBox(playerid, showItem[playerid][2], 0);
PlayerTextDrawSetProportional(playerid, showItem[playerid][2], 1);
PlayerTextDrawSetSelectable(playerid, showItem[playerid][2], 0);

showItem[playerid][3] = CreatePlayerTextDraw(playerid, 284.000000, 212.000000, "Keterangan : ~n~asdasd~n~asdasd~n~askdjaskj qkwjel kq");
PlayerTextDrawFont(playerid, showItem[playerid][3], 2);
PlayerTextDrawLetterSize(playerid, showItem[playerid][3], 0.258332, 1.600000);
PlayerTextDrawTextSize(playerid, showItem[playerid][3], 483.500000, 140.500000);
PlayerTextDrawSetOutline(playerid, showItem[playerid][3], 1);
PlayerTextDrawSetShadow(playerid, showItem[playerid][3], 0);
PlayerTextDrawAlignment(playerid, showItem[playerid][3], 1);
PlayerTextDrawColor(playerid, showItem[playerid][3], -1);
PlayerTextDrawBackgroundColor(playerid, showItem[playerid][3], 255);
PlayerTextDrawBoxColor(playerid, showItem[playerid][3], 50);
PlayerTextDrawUseBox(playerid, showItem[playerid][3], 0);
PlayerTextDrawSetProportional(playerid, showItem[playerid][3], 1);
PlayerTextDrawSetSelectable(playerid, showItem[playerid][3], 0);

showItem[playerid][4] = CreatePlayerTextDraw(playerid, 310.000000, 315.000000, "TUTUP");
PlayerTextDrawFont(playerid, showItem[playerid][4], 2);
PlayerTextDrawLetterSize(playerid, showItem[playerid][4], 0.258332, 1.750000);
PlayerTextDrawTextSize(playerid, showItem[playerid][4], 16.500000, 90.500000);
PlayerTextDrawSetOutline(playerid, showItem[playerid][4], 1);
PlayerTextDrawSetShadow(playerid, showItem[playerid][4], 0);
PlayerTextDrawAlignment(playerid, showItem[playerid][4], 2);
PlayerTextDrawColor(playerid, showItem[playerid][4], -1);
PlayerTextDrawBackgroundColor(playerid, showItem[playerid][4], 255);
PlayerTextDrawBoxColor(playerid, showItem[playerid][4], 200);
PlayerTextDrawUseBox(playerid, showItem[playerid][4], 1);
PlayerTextDrawSetProportional(playerid, showItem[playerid][4], 1);
PlayerTextDrawSetSelectable(playerid, showItem[playerid][4], 1);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
