/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

#include <a_samp>

new PlayerText:PlayerTD[MAX_PLAYERS][6];
new PlayerText:showItem[MAX_PLAYERS];

public OnFilterScriptInit()
{
	return 1;
}

public OnFilterScriptExit()
{
	return 1;
}

public OnPlayerConnect(playerid)
{
	showItem[playerid] = CreatePlayerTextDraw(playerid, 314.000000, 98.000000, "_");
	PlayerTextDrawFont(playerid, showItem[playerid], 1);
	PlayerTextDrawLetterSize(playerid, showItem[playerid], 10.804162, 27.150005);
	PlayerTextDrawTextSize(playerid, showItem[playerid], 40.000000, 356.000000);
	PlayerTextDrawSetOutline(playerid, showItem[playerid], 1);
	PlayerTextDrawSetShadow(playerid, showItem[playerid], 0);
	PlayerTextDrawAlignment(playerid, showItem[playerid], 2);
	PlayerTextDrawColor(playerid, showItem[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, showItem[playerid], 255);
	PlayerTextDrawBoxColor(playerid, showItem[playerid], 207);
	PlayerTextDrawUseBox(playerid, showItem[playerid], 1);
	PlayerTextDrawSetProportional(playerid, showItem[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, showItem[playerid], 0);

	showItem[playerid][0] = CreatePlayerTextDraw(playerid, 157.000000, 145.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, showItem[playerid][0], 5);
	PlayerTextDrawLetterSize(playerid, showItem[playerid][0], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, showItem[playerid][0], 112.500000, 150.000000);
	PlayerTextDrawSetOutline(playerid, showItem[playerid][0], 0);
	PlayerTextDrawSetShadow(playerid, showItem[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, showItem[playerid][0], 1);
	PlayerTextDrawColor(playerid, showItem[playerid][0], -1);
	PlayerTextDrawBackgroundColor(playerid, showItem[playerid][0], -131);
	PlayerTextDrawBoxColor(playerid, showItem[playerid][0], -1);
	PlayerTextDrawUseBox(playerid, showItem[playerid][0], 0);
	PlayerTextDrawSetProportional(playerid, showItem[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, showItem[playerid][0], 0);
	PlayerTextDrawSetPreviewModel(playerid, showItem[playerid][0], 0);
	PlayerTextDrawSetPreviewRot(playerid, showItem[playerid][0], -10.000000, 0.000000, -20.000000, 1.000000);
	PlayerTextDrawSetPreviewVehCol(playerid, showItem[playerid][0], 1, 1);

	showItem[playerid][1] = CreatePlayerTextDraw(playerid, 143.000000, 110.000000, "Info Item ~g~Cosinus");
	PlayerTextDrawFont(playerid, showItem[playerid][1], 3);
	PlayerTextDrawLetterSize(playerid, showItem[playerid][1], 0.412499, 2.199999);
	PlayerTextDrawTextSize(playerid, showItem[playerid][1], 484.500000, 17.000000);
	PlayerTextDrawSetOutline(playerid, showItem[playerid][1], 1);
	PlayerTextDrawSetShadow(playerid, showItem[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, showItem[playerid][1], 1);
	PlayerTextDrawColor(playerid, showItem[playerid][1], -1);
	PlayerTextDrawBackgroundColor(playerid, showItem[playerid][1], 255);
	PlayerTextDrawBoxColor(playerid, showItem[playerid][1], 50);
	PlayerTextDrawUseBox(playerid, showItem[playerid][1], 1);
	PlayerTextDrawSetProportional(playerid, showItem[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, showItem[playerid][1], 0);

	showItem[playerid][3] = CreatePlayerTextDraw(playerid, 284.000000, 201.000000, "Keterangan :");
	PlayerTextDrawFont(playerid, showItem[playerid][3], 2);
	PlayerTextDrawLetterSize(playerid, showItem[playerid][3], 0.216663, 1.299997);
	PlayerTextDrawTextSize(playerid, showItem[playerid][3], 492.000000, 36.500000);
	PlayerTextDrawSetOutline(playerid, showItem[playerid][3], 1);
	PlayerTextDrawSetShadow(playerid, showItem[playerid][3], 0);
	PlayerTextDrawAlignment(playerid, showItem[playerid][3], 1);
	PlayerTextDrawColor(playerid, showItem[playerid][3], -1);
	PlayerTextDrawBackgroundColor(playerid, showItem[playerid][3], 255);
	PlayerTextDrawBoxColor(playerid, showItem[playerid][3], 50);
	PlayerTextDrawUseBox(playerid, showItem[playerid][3], 1);
	PlayerTextDrawSetProportional(playerid, showItem[playerid][3], 1);
	PlayerTextDrawSetSelectable(playerid, showItem[playerid][3], 0);

	showItem[playerid][4] = CreatePlayerTextDraw(playerid, 319.000000, 347.000000, "TUTUP");
	PlayerTextDrawFont(playerid, showItem[playerid][4], 2);
	PlayerTextDrawLetterSize(playerid, showItem[playerid][4], 0.258332, 1.550000);
	PlayerTextDrawTextSize(playerid, showItem[playerid][4], 16.500000, 90.500000);
	PlayerTextDrawSetOutline(playerid, showItem[playerid][4], 1);
	PlayerTextDrawSetShadow(playerid, showItem[playerid][4], 0);
	PlayerTextDrawAlignment(playerid, showItem[playerid][4], 2);
	PlayerTextDrawColor(playerid, showItem[playerid][4], -1);
	PlayerTextDrawBackgroundColor(playerid, showItem[playerid][4], 255);
	PlayerTextDrawBoxColor(playerid, showItem[playerid][4], 200);
	PlayerTextDrawUseBox(playerid, showItem[playerid][4], 1);
	PlayerTextDrawSetProportional(playerid, showItem[playerid][4], 1);
	PlayerTextDrawSetSelectable(playerid, showItem[playerid][4], 1);

	showItem[playerid][6] = CreatePlayerTextDraw(playerid, 284.000000, 148.000000, "Nama Item : Paintjob Stiker Kendaraan");
	PlayerTextDrawFont(playerid, showItem[playerid][6], 2);
	PlayerTextDrawLetterSize(playerid, showItem[playerid][6], 0.216663, 1.299997);
	PlayerTextDrawTextSize(playerid, showItem[playerid][6], 492.000000, 36.500000);
	PlayerTextDrawSetOutline(playerid, showItem[playerid][6], 1);
	PlayerTextDrawSetShadow(playerid, showItem[playerid][6], 0);
	PlayerTextDrawAlignment(playerid, showItem[playerid][6], 1);
	PlayerTextDrawColor(playerid, showItem[playerid][6], -1);
	PlayerTextDrawBackgroundColor(playerid, showItem[playerid][6], 255);
	PlayerTextDrawBoxColor(playerid, showItem[playerid][6], 50);
	PlayerTextDrawUseBox(playerid, showItem[playerid][6], 1);
	PlayerTextDrawSetProportional(playerid, showItem[playerid][6], 1);
	PlayerTextDrawSetSelectable(playerid, showItem[playerid][6], 0);

	showItem[playerid][2] = CreatePlayerTextDraw(playerid, 284.000000, 176.000000, "Jumlah Item : 100000");
	PlayerTextDrawFont(playerid, showItem[playerid][2], 2);
	PlayerTextDrawLetterSize(playerid, showItem[playerid][2], 0.216663, 1.299997);
	PlayerTextDrawTextSize(playerid, showItem[playerid][2], 492.000000, 36.500000);
	PlayerTextDrawSetOutline(playerid, showItem[playerid][2], 1);
	PlayerTextDrawSetShadow(playerid, showItem[playerid][2], 0);
	PlayerTextDrawAlignment(playerid, showItem[playerid][2], 1);
	PlayerTextDrawColor(playerid, showItem[playerid][2], -1);
	PlayerTextDrawBackgroundColor(playerid, showItem[playerid][2], 255);
	PlayerTextDrawBoxColor(playerid, showItem[playerid][2], 50);
	PlayerTextDrawUseBox(playerid, showItem[playerid][2], 1);
	PlayerTextDrawSetProportional(playerid, showItem[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, showItem[playerid][2], 0);

	return 1;
}

public OnPlayerDisconnect(playerid, reason)
{
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][0]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][1]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][2]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][3]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][4]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][5]);
	PlayerTextDrawDestroy(playerid, showItem[playerid]);
	return 1;
}

public OnPlayerCommandText(playerid, cmdtext[])
{
	if(!strcmp(cmdtext, "/tdtest", true))
	{
		PlayerTextDrawShow(playerid, PlayerTD[playerid][0]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][1]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][2]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][3]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][4]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][5]);
		PlayerTextDrawShow(playerid, showItem[playerid]);
		SelectTextDraw(playerid, 0xFF0000FF);
		return 1;
	}
	return 0;
}
